# Conclusion {-}

This thesis is composed of three essays that explore wide-ranging aspects of international agreements. The chapters are disparate in the puzzles they analyse, and the approaches taken to tackle them. First, Chapter 2 uses an empirical approach and novel firm-level data to establish firm behaviour following the signing of a Foreign Investment Protection Agreement between Canada and Peru. Second, Chapter 3 uses a dynamic programming structural approach to evaluate the impact of having tariffs tied down by international agreements when a government is confronted with a sovereign debt crisis. Third, Chapter 4 uses the immense amount of international trade and detailed data that was generated from these international agreements to compare changes in consumption patterns for countries that saw different increases in the income shares of the top 1% of income recipients.

In Chapter 2 it is demonstrated that while there was a large increase in investment from Canada into Peru after the Canada-Peru FIPA was enacted, it did not lead to Canadian firms offshoring production to Peru. Even though the aggregate and industry-level data seemed to indicate there might be offshoring, the detailed firm-level demonstrated this was not the case. More likely explanations are that the investment Canadian firms made was as greenfield FDI to secure mining rights in Peru, or that it was used to gain more direct access to sell products in adjoining countries. It is outside the scope of the Canadian firm-level data to be able to answer how this Canadian investment was used.

In Chapter 3 a theoretical model is used to simulate the use of tariffs as an instrument for governments to utilise when faced with a sovereign default crisis. It explores the tradeoff the sovereign faces when raising tariffs between being able to raise higher revenues to continue borrowing and lowering output. Tariff revenues are especially crucial for countries with less formal institutions, who are unable to readily collect other forms of tax revenues. This chapter highlights the importance of schemes such as the Everything but Arms, a European Union program, which allows for Least Developed Countries within the WTO to unilaterally export goods tariff-free while being able to maintain some freedom over their own tariffs. More importantly, it calls to consideration the issue of these countries needing flexibility over their tariff rates when negotiating regional trade agreements. 

In Chapter 4 an empirical analysis uses widely available import data to attempt to capture changes in consumption patterns for countries that saw a surge in the top 1\% share of income versus those that did not observe such a surge. It is found that there was no larger increase in the imports of luxury goods for countries that experienced larger surges in the top share of income. This acts as evidence against a large increase in top-end consumption inequality associated with this top income surge. Overall, the insights that this dissertation provides improves our understanding of international agreements and the data that they generate. 
